### ISSUE TITLE
Retrofit @body with @multipart having Issue

### ISSUE THREAD

**Issue by vishalpatel1327** [square/retrofit#1785]
# for image Multipart

case 1. (Which i done)

 service params :

```
{ "id":"1","name":"vishal","image/file":""} 
```

At that time my API of retrofit

```
@Multipart
@POST("webservice")
Call<SignUpResp> loadSignupMultipart(@Part("description") RequestBody description, @Part MultipartBody.Part file, @QueryMap HashMap<String, String> params);
```

case 2. (Where i confuse)  with @Body class<UploadwithImage>

```
{
"methodName":"submitLevel1Part2Icon",
"userid":"150",
"headerData":{
    "fiction":{
        "icon_type":"1",
        "icon_id":"3"},
    "nonfiction":{
        "icon_type":"2",
        "icon_id":"4"},
    "relation":{
        "icon_type":"3",
        "icon_id":"0",
        "name":"Ronak",
        "relative_image":"<File>",
        "relation_id":"3"},
    "self":{
        "icon_type":"4",
        "icon_id":"0"}
    }
}
```

I am trying this API

```
 @Multipart
 @POST("webservice")
 Call<SubmitLevel1Part2IconResp> loadLevel1halfIconswithImage(@Part("description") RequestBody description, @Part MultipartBody.Part file, @Body UploadwithImage uploadImage);
```
# at java side

 /**
             \* code for multipart
             */

```
        // create RequestBody instance from file
        RequestBody requestFile =
                RequestBody.create(MediaType.parse("multipart/form-data"), fileUpload);

        // MultipartBody.Part is used to send also the actual file name
        MultipartBody.Part body =
                MultipartBody.Part.createFormData("methodName[headerData][relation][relative_image]", fileUpload.getName(), requestFile);

        // add another part within the multipart request
        String descriptionString = "hello, this is description speaking";
        RequestBody description =
                RequestBody.create(
                        MediaType.parse("multipart/form-data"), descriptionString);


        call = service.loadLevel1halfIconswithImage(description, body, levelOneHalfIcons);
```

 i cant understand its return
erroor:

> "@Body parameters cannot be used with form or multi-part encoding"

Pls help

i need @Body  with multipart But how

**Comment by anelrh26** [comment]
Hello, I don't know if this helps, but I had some issue with the multipart before, and this is how I fixed.

Look the accepted answer

http://stackoverflow.com/questions/21582453/multipart-request-using-retrofit-1-8-0-not-working

**Comment by liyajun2013** [comment]
@vishalpatel1327  have you solved it？how to solve it？

**Comment by vishalpatelinexture** [comment]
no doesnt solve this type of functionality doesnt provided by Retrofit

i just change my  webservices  

upload file parameter  at begining of object like 


```
`{
"methodName":"submitLevel1Part2Icon",
"userid":"150",
 "relative_image":"<File>",
"headerData":{
    "fiction":{
        "icon_type":"1",
        "icon_id":"3"},
    "nonfiction":{
        "icon_type":"2",
        "icon_id":"4"},
    "relation":{
        "icon_type":"3",
        "icon_id":"0",
        "name":"Ronak",
        "relation_id":"3"},
    "self":{
        "icon_type":"4",
        "icon_id":"0"}
    }
}`

```

**Comment by vishalpatel1327** [comment]
no doesnt solve this type of functionality doesnt provided by Retrofit

i just change my  webservices  

upload file parameter  at begining of object like 


```
`{
"methodName":"submitLevel1Part2Icon",
"userid":"150",
 "relative_image":"<File>",
"headerData":{
    "fiction":{
        "icon_type":"1",
        "icon_id":"3"},
    "nonfiction":{
        "icon_type":"2",
        "icon_id":"4"},
    "relation":{
        "icon_type":"3",
        "icon_id":"0",
        "name":"Ronak",
        "relation_id":"3"},
    "self":{
        "icon_type":"4",
        "icon_id":"0"}
    }
}`

```

**Comment by JakeWharton** [comment]
If you're sending JSON with your image upload then that should be another `@Part`, not a `@Body`. When you use `@Multipart` you are specifying that the body is a multipart request and so all that's available for contributing to that body is `@Part`s.

**Comment by vishalpatel1327** [comment]
Sir, I cant understand   

can u pls make callback for like 
 

> @Multipart
>  @POST("webservice")
>  Call<SubmitLevel1Part2IconResp> loadLevel1halfIconswithImage(@Part("description") RequestBody description, @Part MultipartBody.Part file, @Body UploadwithImage uploadImage);
> 


of

> {
> "methodName":"submitLevel1Part2Icon",
> "userid":"150",
> "headerData":{
>     "fiction":{
>         "icon_type":"1",
>         "icon_id":"3"},
>     "nonfiction":{
>         "icon_type":"2",
>         "icon_id":"4"},
>     "relation":{
>         "icon_type":"3",
>         "icon_id":"0",
>         "name":"Ronak",
>         "relative_image":"<File>",
>         "relation_id":"3"},
>     "self":{
>         "icon_type":"4",
>         "icon_id":"0"}
>     }
> }




so I can understand better
