### ISSUE TITLE
Use a better error message when multiple callback types are in use.

### ISSUE THREAD

**Issue by IgorGanapolsky** [square/retrofit#827]
Hello,
I am using retrofit 1.9.0, and getting a strange error:
>  Error: retrofit.RetrofitError:: No Retrofit annotation found. (parameter #2)

I defined my api method like this:
`@POST("/login")
    Observable<Customer> doEmailLogin(@Body LoginBody loginBody, Callback<ResponseBody> callback);`

What could be causing this error with my Callback interface??

Thank you,
Igor

**Comment by JakeWharton** [comment]
Both returning the observable and the callback are mechanisms of how the request is executed. You don't need both, only one.

In this case, Retrofit sees the observable as the way the request will be executed and treats all of the method parameters as part of how the request will be created. Since the callback parameter has no annotation, it thinks this is an error. Simply remove the callback or change the return type to `void`.

I'll leave this issue open as a reminder to create a better error message for this case.

**Comment by IgorGanapolsky** [comment]
But according to your logic, there is no way for me to parse the ResponseBody.  AFAIK, I need a custom Callback for that.  Am I wrong?

**Comment by JakeWharton** [comment]
Callback is a mechanism of notifying you of data just as the observable is. There is no way to receive both the `ResponseBody` _and_ a `Customer` instance. They both represent the same thing in different forms.

**Comment by IgorGanapolsky** [comment]
Oh wait, I just had to do:
`                .subscribe(new Subscriber<Response>() {
`

**Comment by IgorGanapolsky** [comment]
@JakeWharton  Thanks for the tip.  Have some @changetip bitcoin $1 on me.

**Comment by changetip** [comment]
Hi @jakewharton, @IgorGanapolsky sent you a Bitcoin tip worth 4,251 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/821619)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by JakeWharton** [comment]
This was fixed as a side-effect of the massive #845 change. The v2.0 release will have better messaging around erroneous usage of the execution mechanism.

**Comment by dinhthaidaica** [comment]
Could you tell me how it was resolve in v  2.0 ? 
I have same problem and still get stuck, can not call '.subscribe(new Subscriber<Response>() {' any more
